{% set name = "aimsgb" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aimsgb-{{ version }}.tar.gz
  sha256: 4fc39da404a988d0e2fa34e0222570279a9607fe85b16ede2012c215bcc4c075

build:
  entry_points:
    - aimsgb = aimsgb.agb:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=18.0
    - pip
  run:
    - python >={{ python_min }}
    - pymatgen
    - mp-api
    - numpy
    - pytest

test:
  imports:
    - aimsgb
  commands:
    - pip check
    - aimsgb --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://aimsgb.org
  summary: aimsgb is a python library for generatng the atomic coordinates of periodic grain boundaries.Copyright © 2018 The Regents of the University of California.All Rights Reserved. See more in Copyright.
  license: BSD-4-Clause
  license_file:
    - COPYRIGHT.rst

extra:
  recipe-maintainers:
    - jan-janssen
