{% set name = "aimsgb" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aimsgb-{{ version }}.tar.gz
  sha256: 04416bf35b4464c56d96189ced6ee2c2385a8c4153a3e9f66c2e59630737352e

build:
  number: 0
  noarch: python
  entry_points:
    - aimsgb = aimsgb.agb:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=18.0
  run:
    - pymatgen
    - python >=3.6

test:
  imports:
    - aimsgb
  commands:
    - pip check
    - aimsgb --help
  requires:
    - pip

about:
  home: https://github.com/ksyang2013/aimsgb
  license: MIT
  license_family: MIT
  license_file: COPYRIGHT.rst
  summary: Ab-initio Interface Materials Simulation Project for Grain Boundaries (AIMSGB)
  description: |
    aimsgb, an efficient and open-source Python library for generating
    atomic coordinates in periodic grain boundary models. It is designed
    to construct various grain boundary structures from cubic and
    non-cubic initial configurations. A convenient command line tool has
    also been provided to enable easy and fast construction of tilt and 
    twist boundaries by assigining the degree of fit (Î£), rotation axis,
    grain boundary plane and initial crystal structure. aimsgb is expected
    to greatly accelerate the theoretical investigation of grain boundary
    properties and facilitate the experimental analysis of grain boundary
    structures as well.
  doc_url: https://github.com/ksyang2013/aimsgb
  dev_url: https://github.com/ksyang2013/aimsgb

extra:
  recipe-maintainers:
    - jan-janssen
